// <auto-generated />
namespace EmpireMap.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PlayerModification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlayerModification));
        
        string IMigrationMetadata.Id
        {
            get { return "201302170000096_PlayerModification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
