// <auto-generated />
namespace EmpireMap.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CastleStorage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CastleStorage));
        
        string IMigrationMetadata.Id
        {
            get { return "201303311638278_CastleStorage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
